In [1]:
from scipy import linalg as sl
import numpy as np

In [2]:
rows = 750

In [3]:
result = sl.pascal(rows, kind="lower")

In [4]:
print(result)

[[1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 2 1 ... 0 0 0]
 ...
 [1 747 278631 ... 1 0 0]
 [1 748 279378 ... 748 1 0]
 [1 749 280126 ... 280126 749 1]]


In [6]:
i = 0
for row in result:
    #print(row % 2 == 1)
    print("row: ", i, "     odds: ", np.sum(row % 2 == 1))
    i += 1

row:  0      odds:  1
row:  1      odds:  2
row:  2      odds:  2
row:  3      odds:  4
row:  4      odds:  2
row:  5      odds:  4
row:  6      odds:  4
row:  7      odds:  8
row:  8      odds:  2
row:  9      odds:  4
row:  10      odds:  4
row:  11      odds:  8
row:  12      odds:  4
row:  13      odds:  8
row:  14      odds:  8
row:  15      odds:  16
row:  16      odds:  2
row:  17      odds:  4
row:  18      odds:  4
row:  19      odds:  8
row:  20      odds:  4
row:  21      odds:  8
row:  22      odds:  8
row:  23      odds:  16
row:  24      odds:  4
row:  25      odds:  8
row:  26      odds:  8
row:  27      odds:  16
row:  28      odds:  8
row:  29      odds:  16
row:  30      odds:  16
row:  31      odds:  32
row:  32      odds:  2
row:  33      odds:  4
row:  34      odds:  4
row:  35      odds:  8
row:  36      odds:  4
row:  37      odds:  8
row:  38      odds:  8
row:  39      odds:  16
row:  40      odds:  4
row:  41      odds:  8
row:  42      odds:  8
row:  43      

row:  395      odds:  32
row:  396      odds:  16
row:  397      odds:  32
row:  398      odds:  32
row:  399      odds:  64
row:  400      odds:  8
row:  401      odds:  16
row:  402      odds:  16
row:  403      odds:  32
row:  404      odds:  16
row:  405      odds:  32
row:  406      odds:  32
row:  407      odds:  64
row:  408      odds:  16
row:  409      odds:  32
row:  410      odds:  32
row:  411      odds:  64
row:  412      odds:  32
row:  413      odds:  64
row:  414      odds:  64
row:  415      odds:  128
row:  416      odds:  8
row:  417      odds:  16
row:  418      odds:  16
row:  419      odds:  32
row:  420      odds:  16
row:  421      odds:  32
row:  422      odds:  32
row:  423      odds:  64
row:  424      odds:  16
row:  425      odds:  32
row:  426      odds:  32
row:  427      odds:  64
row:  428      odds:  32
row:  429      odds:  64
row:  430      odds:  64
row:  431      odds:  128
row:  432      odds:  16
row:  433      odds:  32
row:  434      odds:  32


In [7]:
#end
